// import { Inter } from "next/font/google";
import "./globals.css";
// import { Html } from "next/document";

// const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./providers";
export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout ( { children } ) {
  return (
    <html lang="en">
      <body className='overflow-x-hidden antialiased font-sans bg-white text-gray-900 dark:bg-black dark:text-white transition-all transition-duration-[0.7s]'>
        <Providers>
          <main>{ children }</main>
        </Providers>

      </body>
    </html>


  );
}
